version: '27.3.1'
services:
  nest-dev:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs
    networks:
      - freecodecamp
networks:
  freecodecamp: